version: '3'
services:
  e-store-eureka-service:
    container_name: e-store-eureka-service
    image: e-store-eureka-service:1.0.1
    ports:
      - "3467:3467"
    networks:
      - e-store
  e-store-api-gateway:
    container_name: e-store-api-gateway
    image: e-store-api-gateway:1.0.2
    ports:
      - "8080:8080"
    networks:
      - e-store
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - e-store-eureka-service
  e-store-order-service:
    container_name: e-store-order-service
    image: e-store-order-service:1.0.2
    networks:
      - e-store
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - e-store-api-gateway
      - e-store-eureka-service
  e-store-payment-service:
      container_name: e-store-payment-service
      image: e-store-payment-service:1.0.2
      networks:
        - e-store
      environment:
        - SPRING_PROFILES_ACTIVE=docker
      depends_on:
        - e-store-api-gateway
        - e-store-eureka-service
  e-store-user-service:
      container_name: e-store-user-service
      image: e-store-user-service:1.0.2
      networks:
        - e-store
      environment:
        - SPRING_PROFILES_ACTIVE=docker
      depends_on:
        - e-store-api-gateway
        - e-store-eureka-service

networks:
  e-store:
    driver: bridge